// client/src/pages/Home.vue
<script lang="ts" setup>
import { onMounted } from 'vue';
import '@n8n/chat/style.css';
import { createChat } from '@n8n/chat';
import Header from '../components/Header.vue';
import HeroSection from '../components/HeroSection.vue';
import FeaturesSection from '../components/FeaturesSection.vue';
import AIAssistantSection from '../components/AIAssistantSection.vue';
import MinisteriesSection from '../components/MinisteriesSection.vue';
import TestimonialsSection from '../components/TestimonialsSection.vue';
import CtaSection from '../components/CtaSection.vue';
import Footer from '../components/Footer.vue';

// N8N Chat integration
onMounted(() => {
  createChat({
    webhookUrl: import.meta.env.VITE_N8N_WEBHOOK_URL || 'YOUR_PRODUCTION_WEBHOOK_URL'
  });
});
</script>

<template>
  <div class="min-h-screen bg-togo-light flex flex-col">
    <Header />
    <main>
      <HeroSection />
      <FeaturesSection />
      <AIAssistantSection />
      <MinisteriesSection />
      <TestimonialsSection />
      <CtaSection />
    </main>
    <Footer />
    
    <!-- Chat Button -->
    <div class="chat-button">
      <button 
        class="bg-primary text-white rounded-full p-4 shadow-lg hover:bg-primary/90 transition duration-300 flex items-center justify-center animate-pulse"
        aria-label="Ouvrir le chat avec l'assistant IA"
      >
        <i class="fas fa-comments text-2xl"></i>
      </button>
    </div>
  </div>
</template>

// client/src/pages/Home.tsx
import { useEffect } from "react";
import Header from "@/components/Header";
import HeroSection from "@/components/HeroSection";
import FeaturesSection from "@/components/FeaturesSection";
import AIAssistantSection from "@/components/AIAssistantSection";
import MinisteriesSection from "@/components/MinisteriesSection";
import TestimonialsSection from "@/components/TestimonialsSection";
import CtaSection from "@/components/CtaSection";
import Footer from "@/components/Footer";
import { initializeN8NChat } from "@/lib/n8nChat";

export default function Home() {
  useEffect(() => {
    // Initialize N8N Chat
    initializeN8NChat();
  }, []);

  return (
    <div className="min-h-screen bg-background flex flex-col">
      <Header />
      <main>
        <HeroSection />
        <FeaturesSection />
        <AIAssistantSection />
        <MinisteriesSection />
        <TestimonialsSection />
        <CtaSection />
      </main>
      <Footer />
      
      {/* Chat Button */}
      <div className="chat-button">
        <button 
          className="bg-primary text-white rounded-full p-4 shadow-lg hover:bg-primary/90 transition duration-300 flex items-center justify-center animate-pulse"
          aria-label="Ouvrir le chat avec l'assistant IA"
          id="open-n8n-chat"
        >
          <i className="fas fa-comments text-2xl"></i>
        </button>
      </div>
    </div>
  );
}
