// client/src/components/AIAssistantSection.tsx
export default function AIAssistantSection() {
  return (
    <section className="py-24 bg-gray-50">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-12 items-center">
          <div className="order-2 md:order-1">
            <div className="relative">
              <div className="bg-white p-6 rounded-xl shadow-xl max-w-md mx-auto">
                <div className="flex items-center border-b border-gray-200 pb-4 mb-4">
                  <div className="w-10 h-10 bg-primary rounded-full flex items-center justify-center mr-3">
                    <i className="fas fa-robot text-white"></i>
                  </div>
                  <h3 className="font-bold text-lg">Assistant e-Services</h3>
                </div>
                
                <div className="space-y-4">
                  <div className="bg-gray-100 p-3 rounded-lg rounded-tl-none">
                    <p className="text-gray-800">Bonjour, comment puis-je vous aider aujourd'hui avec les services administratifs du Togo?</p>
                  </div>
                  
                  <div className="bg-blue-50 p-3 rounded-lg rounded-tr-none ml-auto">
                    <p className="text-gray-800">Quelles sont les démarches pour obtenir un permis de conduire au Togo?</p>
                  </div>
                  
                  <div className="bg-gray-100 p-3 rounded-lg rounded-tl-none">
                    <p className="text-gray-800">Pour obtenir un permis de conduire au Togo, voici les étapes à suivre:</p>
                    <ol className="list-decimal pl-5 mt-2 space-y-1 text-gray-700">
                      <li>S'inscrire dans une auto-école agréée</li>
                      <li>Passer l'examen théorique (code de la route)</li>
                      <li>Passer l'examen pratique de conduite</li>
                      <li>Une fois réussi, déposer un dossier à la Direction des Transports Routiers</li>
                      <li>Payer les frais de dossier et d'établissement</li>
                    </ol>
                    <p className="mt-2 text-gray-800">Souhaitez-vous connaître les documents nécessaires pour constituer le dossier?</p>
                  </div>
                  
                  <div className="relative">
                    <span className="flex h-3 w-3 absolute -bottom-5 left-0">
                      <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-primary opacity-75"></span>
                      <span className="relative inline-flex rounded-full h-3 w-3 bg-primary"></span>
                    </span>
                  </div>
                </div>
              </div>
              
              <div className="absolute -bottom-6 -right-6 w-32 h-32 bg-secondary rounded-full z-[-1] opacity-50"></div>
              <div className="absolute -top-6 -left-6 w-24 h-24 bg-primary rounded-full z-[-1] opacity-30"></div>
            </div>
          </div>
          
          <div className="order-1 md:order-2">
            <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-6">Notre Assistant Virtuel à Votre Service</h2>
            <p className="text-xl text-gray-600 mb-8">
              Posez vos questions en langage naturel et obtenez des réponses précises sur les démarches administratives au Togo.
            </p>
            
            <div className="space-y-4">
              {[
                {
                  icon: "fa-comments-alt",
                  title: "Conversation Naturelle",
                  description: "Dialoguez comme avec un agent réel pour obtenir des informations personnalisées."
                },
                {
                  icon: "fa-clock",
                  title: "Disponible 24h/24",
                  description: "Accédez aux informations à tout moment, sans contrainte d'horaires."
                },
                {
                  icon: "fa-check-double",
                  title: "Information Précise",
                  description: "Obtenez des réponses vérifiées et à jour sur les procédures administratives."
                }
              ].map((feature, index) => (
                <div key={index} className="flex items-start">
                  <div className="mt-1 bg-primary/10 rounded-full p-2 mr-4 flex-shrink-0">
                    <i className={`fas ${feature.icon} text-primary`}></i>
                  </div>
                  <div>
                    <h3 className="font-semibold text-lg text-gray-900">{feature.title}</h3>
                    <p className="text-gray-600">{feature.description}</p>
                  </div>
                </div>
              ))}
            </div>
            
            <button 
              className="mt-8 bg-primary hover:bg-primary/90 text-white px-6 py-3 rounded-lg font-medium transition-colors duration-300 inline-flex items-center"
              onClick={() => {
                const heroButton = document.getElementById('hero-chat-button');
                if (heroButton) {
                  heroButton.click();
                }
              }}
            >
              <i className="fas fa-robot mr-2"></i>
              Essayer l'assistant maintenant
            </button>
          </div>
        </div>
      </div>
    </section>
  );
}

// client/src/components/AIAssistantSection.vue
<script lang="ts" setup>
import { ref } from 'vue';

const inputMessage = ref('');
const messages = ref([
  {
    type: 'ai',
    content: 'Bonjour ! Je suis l\'assistant virtuel du gouvernement togolais. Comment puis-je vous aider aujourd\'hui ?'
  },
  {
    type: 'user',
    content: 'Je voudrais renouveler ma carte d\'identité nationale.'
  },
  {
    type: 'ai',
    content: 'Pour renouveler votre carte d\'identité nationale, voici les étapes à suivre :',
    steps: [
      'Préparez une copie de votre acte de naissance',
      'Une photo d\'identité récente',
      'Un justificatif de domicile'
    ],
    followUp: 'Souhaitez-vous que je vous aide à prendre rendez-vous ?'
  }
]);

const benefits = [
  {
    icon: 'fas fa-check',
    title: 'Réponses Instantanées',
    description: 'Obtenez des informations précises sans attente ni file d\'attente.'
  },
  {
    icon: 'fas fa-check',
    title: 'Guidage Personnalisé',
    description: 'Recevez des instructions adaptées à votre situation spécifique.'
  },
  {
    icon: 'fas fa-check',
    title: 'Multilangue',
    description: 'Communiquez dans la langue de votre choix pour plus de confort.'
  }
];

const sendMessage = () => {
  if (!inputMessage.value.trim()) return;
  
  // Add user message
  messages.value.push({
    type: 'user',
    content: inputMessage.value
  });
  
  // In a real app, you would send this to an API and get a response
  // For now, we'll simulate an AI response
  setTimeout(() => {
    messages.value.push({
      type: 'ai',
      content: 'Je vous ai bien compris. Je suis là pour vous aider avec toutes vos questions concernant les services gouvernementaux.'
    });
  }, 1000);
  
  // Clear input
  inputMessage.value = '';
};
</script>

<template>
  <section class="py-20 bg-gradient-to-b from-white to-togo-light">
    <div class="container mx-auto px-4 sm:px-6 lg:px-8">
      <div class="grid grid-cols-1 md:grid-cols-2 gap-10 items-center">
        <div class="order-2 md:order-1">
          <div class="bg-white rounded-2xl shadow-xl p-6 relative">
            <div class="bg-primary rounded-t-xl p-4 -mt-6 -mx-6 mb-4">
              <div class="flex items-center space-x-3">
                <div class="w-3 h-3 bg-red-500 rounded-full"></div>
                <div class="w-3 h-3 bg-yellow-500 rounded-full"></div>
                <div class="w-3 h-3 bg-green-500 rounded-full"></div>
                <span class="text-white ml-4 font-medium">Assistant IA du Gouvernement</span>
              </div>
            </div>
            
            <div class="space-y-4 max-h-80 overflow-y-auto p-2">
              <div 
                v-for="(message, index) in messages" 
                :key="index"
                :class="[
                  'flex items-start space-x-3', 
                  message.type === 'user' ? 'justify-end' : ''
                ]"
              >
                <!-- AI Icon (only for AI messages) -->
                <div 
                  v-if="message.type === 'ai'"
                  class="bg-primary text-white p-2 rounded-full flex items-center justify-center w-8 h-8"
                >
                  <i class="fas fa-robot"></i>
                </div>
                
                <!-- Message Bubble -->
                <div 
                  :class="[
                    message.type === 'ai' ? 'bg-togo-light' : 'bg-primary/10',
                    'rounded-lg p-3 max-w-xs'
                  ]"
                >
                  <p class="text-togo-dark">{{ message.content }}</p>
                  
                  <!-- Steps for AI messages that have steps -->
                  <ol 
                    v-if="message.steps && message.steps.length"
                    class="list-decimal pl-5 mt-2 text-togo-dark space-y-1"
                  >
                    <li v-for="(step, stepIndex) in message.steps" :key="stepIndex">
                      {{ step }}
                    </li>
                  </ol>
                  
                  <!-- Follow-up text if provided -->
                  <p v-if="message.followUp" class="mt-2 text-togo-dark">
                    {{ message.followUp }}
                  </p>
                </div>
                
                <!-- User Icon (only for user messages) -->
                <div 
                  v-if="message.type === 'user'"
                  class="bg-secondary text-togo-dark p-2 rounded-full flex items-center justify-center w-8 h-8"
                >
                  <i class="fas fa-user"></i>
                </div>
              </div>
            </div>
            
            <div class="mt-4 flex items-center bg-gray-100 rounded-lg p-2">
              <input 
                v-model="inputMessage"
                type="text" 
                placeholder="Posez votre question ici..." 
                class="flex-1 bg-transparent border-none focus:outline-none text-togo-dark"
                @keyup.enter="sendMessage"
              />
              <button 
                class="ml-2 bg-primary text-white p-2 rounded-lg"
                @click="sendMessage"
              >
                <i class="fas fa-paper-plane"></i>
              </button>
            </div>
          </div>
        </div>
        
        <div class="order-1 md:order-2">
          <h2 class="text-3xl md:text-4xl font-bold text-togo-dark mb-6">Votre Assistant Numérique Personnel</h2>
          <p class="text-lg text-togo-gray mb-6">Notre assistant IA est disponible 24/7 pour répondre à toutes vos questions concernant les services gouvernementaux togolais.</p>
          
          <div class="space-y-4">
            <div 
              v-for="(benefit, index) in benefits" 
              :key="index"
              class="flex items-start space-x-4"
            >
              <div class="bg-primary/10 p-3 rounded-full flex-shrink-0">
                <i :class="[benefit.icon, 'text-primary']"></i>
              </div>
              <div>
                <h4 class="font-bold text-togo-dark">{{ benefit.title }}</h4>
                <p class="text-togo-gray">{{ benefit.description }}</p>
              </div>
            </div>
          </div>
          
          <button class="mt-8 bg-secondary text-togo-dark px-6 py-3 rounded-lg font-bold text-lg hover:bg-yellow-400 transition duration-300 shadow-lg flex items-center">
            <i class="fas fa-comments mr-2"></i> Discuter avec l'assistant maintenant
          </button>
        </div>
      </div>
    </div>
  </section>
</template>
