// client/src/components/MinisteriesSection.tsx
export default function MinisteriesSection() {
  const ministeries = [
    {
      name: "Ministère de l'Administration Territoriale",
      icon: "fa-building-columns",
      services: ["Délivrance de documents d'identité", "Sécurité civile", "Gestion des collectivités"]
    },
    {
      name: "Ministère de la Justice",
      icon: "fa-gavel",
      services: ["Services judiciaires", "Certificats de nationalité", "Casiers judiciaires"]
    },
    {
      name: "Ministère de l'Éducation",
      icon: "fa-graduation-cap",
      services: ["Inscriptions scolaires", "Bourses d'études", "Diplômes et équivalences"]
    },
    {
      name: "Ministère de la Santé",
      icon: "fa-hospital",
      services: ["Vaccinations", "Cartes sanitaires", "Assistance médicale"]
    },
    {
      name: "Ministère de l'Économie et des Finances",
      icon: "fa-money-bill-wave",
      services: ["Impôts et taxes", "Douanes", "Services du Trésor"]
    },
    {
      name: "Ministère du Commerce",
      icon: "fa-store",
      services: ["Licences commerciales", "Normalisation", "Promotion des exportations"]
    },
    {
      name: "Ministère de l'Agriculture",
      icon: "fa-tractor",
      services: ["Soutien agricole", "Formations techniques", "Subventions"]
    },
    {
      name: "Ministère du Numérique",
      icon: "fa-laptop-code",
      services: ["Services numériques", "Formation digitale", "Infrastructures IT"]
    }
  ];

  return (
    <section id="ministeres" className="py-20 bg-white">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">Ministères et Services</h2>
          <p className="text-xl text-gray-600 max-w-3xl mx-auto">
            Découvrez les différents ministères togolais et leurs services essentiels pour les citoyens et les entreprises.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          {ministeries.map((ministry, index) => (
            <div 
              key={index}
              className="bg-gray-50 border border-gray-100 rounded-xl overflow-hidden hover:shadow-lg transition-shadow duration-300"
            >
              <div className="p-6">
                <div className="w-14 h-14 bg-primary/10 rounded-full flex items-center justify-center mb-4">
                  <i className={`fas ${ministry.icon} text-primary text-2xl`}></i>
                </div>
                <h3 className="text-lg font-bold text-gray-900 mb-3 line-clamp-2 h-14">{ministry.name}</h3>
                <ul className="space-y-2">
                  {ministry.services.map((service, idx) => (
                    <li key={idx} className="flex items-start">
                      <span className="text-primary mr-2 mt-1">
                        <i className="fas fa-circle-check text-sm"></i>
                      </span>
                      <span className="text-gray-700">{service}</span>
                    </li>
                  ))}
                </ul>
                <button 
                  className="mt-4 w-full py-2 px-4 bg-white border border-gray-200 text-primary rounded-lg hover:bg-gray-50 transition-colors duration-300 text-sm font-medium"
                  onClick={() => {
                    const heroButton = document.getElementById('hero-chat-button');
                    if (heroButton) {
                      heroButton.click();
                    }
                  }}
                >
                  <i className="fas fa-info-circle mr-1"></i> Plus d'informations
                </button>
              </div>
            </div>
          ))}
        </div>

        <div className="mt-16 text-center">
          <p className="text-gray-600 mb-6">
            Notre assistant virtuel peut vous fournir des informations détaillées sur les services de chaque ministère.
          </p>
          <button 
            className="bg-primary hover:bg-primary/90 text-white px-6 py-3 rounded-lg font-medium transition-colors duration-300 inline-flex items-center"
            onClick={() => {
              const heroButton = document.getElementById('hero-chat-button');
              if (heroButton) {
                heroButton.click();
              }
            }}
          >
            <i className="fas fa-comments mr-2"></i>
            Poser une question sur un service ministériel
          </button>
        </div>
      </div>
    </section>
  );
}

// client/src/components/MinisteriesSection.vue
<script lang="ts" setup>
const ministries = [
  {
    id: 1,
    name: 'Ministère de l\'Économie et des Finances',
    description: 'Services fiscaux, douanes, budget et trésor public.',
    image: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400',
    tags: ['Impôts', 'Douanes', 'Budget']
  },
  {
    id: 2,
    name: 'Ministère de l\'Administration Territoriale',
    description: 'Services d\'identification nationale, élections et collectivités locales.',
    image: 'https://pixabay.com/get/gc7d5a457e01b5df02c03cb9b3f8a8bebde537fdac9c1cf1304eabe76a91018eb7891ee936bc12102be07302bccc733912aaa37a6584d323c74d68eeeb50d80e6_1280.jpg',
    tags: ['Cartes d\'identité', 'Passeports', 'État civil']
  },
  {
    id: 3,
    name: 'Ministère de la Justice',
    description: 'Services judiciaires, casier judiciaire et légalisation de documents.',
    image: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400',
    tags: ['Casier judiciaire', 'Légalisations', 'Tribunaux']
  },
  {
    id: 4,
    name: 'Ministère de la Santé',
    description: 'Services de santé publique, assurance maladie et pharmacies.',
    image: 'https://images.unsplash.com/photo-1568952433726-3896e3881c65?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400',
    tags: ['Vaccinations', 'Assurance', 'Hôpitaux']
  },
  {
    id: 5,
    name: 'Ministère de l\'Éducation Nationale',
    description: 'Services éducatifs, inscriptions scolaires et examens nationaux.',
    image: 'https://images.unsplash.com/photo-1573497701240-345a300b8d36?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400',
    tags: ['Inscriptions', 'Diplômes', 'Bourses']
  },
  {
    id: 6,
    name: 'Ministère du Travail et de la Fonction Publique',
    description: 'Services d\'emploi, concours administratifs et retraites.',
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400',
    tags: ['Concours', 'Emplois', 'Retraites']
  }
];
</script>

<template>
  <section id="ministeres" class="py-20 bg-togo-light">
    <div class="container mx-auto px-4 sm:px-6 lg:px-8">
      <div class="text-center mb-16">
        <h2 class="text-3xl md:text-4xl font-bold text-togo-dark mb-4">Ministères Participants</h2>
        <p class="text-lg text-togo-gray max-w-3xl mx-auto">Notre application regroupe les services de plusieurs ministères togolais pour simplifier vos démarches administratives.</p>
      </div>
      
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        <div
          v-for="ministry in ministries"
          :key="ministry.id"
          class="bg-white rounded-xl p-6 shadow-md hover:shadow-lg transition duration-300"
        >
          <img 
            :src="ministry.image" 
            :alt="ministry.name" 
            class="w-full h-48 object-cover rounded-lg mb-4"
          />
          <h3 class="text-xl font-bold mb-2 text-togo-dark">{{ ministry.name }}</h3>
          <p class="text-togo-gray mb-4">{{ ministry.description }}</p>
          <div class="flex space-x-2 flex-wrap">
            <span 
              v-for="(tag, tagIndex) in ministry.tags" 
              :key="tagIndex"
              class="bg-primary/10 text-primary px-3 py-1 rounded-full text-sm font-medium mb-2"
            >
              {{ tag }}
            </span>
          </div>
        </div>
      </div>
      
      <div class="mt-12 text-center">
        <p class="text-togo-gray mb-6">Vous avez des questions sur un service spécifique d'un ministère ?</p>
        <button class="bg-secondary text-togo-dark px-6 py-3 rounded-lg font-bold text-lg hover:bg-yellow-400 transition duration-300 shadow-lg inline-flex items-center">
          <i class="fas fa-comments mr-2"></i> Consultez notre assistant IA
        </button>
      </div>
    </div>
  </section>
</template>
