// client/src/components/TestimonialsSection.tsx
export default function TestimonialsSection() {
  const testimonials = [
    {
      name: "Kokou Mensah",
      role: "Entrepreneur",
      image: "https://randomuser.me/api/portraits/men/41.jpg",
      quote: "Grâce à l'assistant virtuel, j'ai pu obtenir toutes les informations nécessaires pour créer mon entreprise au Togo sans devoir me déplacer plusieurs fois dans différents ministères."
    },
    {
      name: "Ama Koffi",
      role: "Étudiante",
      image: "https://randomuser.me/api/portraits/women/43.jpg",
      quote: "Le processus pour demander une bourse d'études était confus, mais l'assistant m'a guidé étape par étape. C'est un gain de temps incroyable !"
    },
    {
      name: "Emmanuel Agbeko",
      role: "Agriculteur",
      image: "https://randomuser.me/api/portraits/men/32.jpg",
      quote: "J'ai pu découvrir les subventions disponibles pour mon exploitation agricole et comprendre comment les demander. L'information est claire et précise."
    }
  ];

  return (
    <section className="py-20 bg-gray-50">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">Ce que disent nos utilisateurs</h2>
          <p className="text-xl text-gray-600 max-w-3xl mx-auto">
            Découvrez comment notre assistant virtuel aide les citoyens togolais dans leurs démarches administratives au quotidien.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {testimonials.map((testimonial, index) => (
            <div 
              key={index}
              className="bg-white rounded-xl shadow-md p-6 relative"
            >
              <div className="absolute top-0 right-0 transform translate-x-4 -translate-y-4">
                <span className="text-5xl text-primary opacity-20">"</span>
              </div>
              
              <div className="mb-6">
                <p className="text-gray-700 italic relative z-10">"{testimonial.quote}"</p>
              </div>
              
              <div className="flex items-center">
                <img 
                  src={testimonial.image} 
                  alt={testimonial.name} 
                  className="w-12 h-12 rounded-full object-cover mr-4"
                />
                <div>
                  <h4 className="font-bold text-gray-900">{testimonial.name}</h4>
                  <p className="text-sm text-gray-600">{testimonial.role}</p>
                </div>
              </div>
            </div>
          ))}
        </div>

        <div className="mt-16 bg-primary/5 border border-primary/10 rounded-xl p-8 text-center">
          <h3 className="text-2xl font-bold text-gray-900 mb-4">Prêt à simplifier vos démarches administratives ?</h3>
          <p className="text-gray-700 mb-6 max-w-2xl mx-auto">
            Notre assistant virtuel est disponible 24h/24 pour répondre à toutes vos questions concernant les services ministériels au Togo.
          </p>
          <button 
            className="bg-primary hover:bg-primary/90 text-white px-6 py-3 rounded-lg font-medium transition-colors duration-300 inline-flex items-center"
            onClick={() => {
              const heroButton = document.getElementById('hero-chat-button');
              if (heroButton) {
                heroButton.click();
              }
            }}
          >
            <i className="fas fa-comments mr-2"></i>
            Essayer maintenant
          </button>
        </div>
      </div>
    </section>
  );
}

// client/src/components/TestimonialsSection.vue
<script lang="ts" setup>
const testimonials = [
  {
    id: 1,
    name: 'Amah K.',
    role: 'Entrepreneur, Lomé',
    rating: 5,
    content: 'Grâce à l\'assistant IA, j\'ai pu renouveler mon passeport sans faire la queue pendant des heures. Le processus était simple et les instructions étaient claires.',
    avatar: 'https://images.unsplash.com/photo-1531384441138-2736e62e0919?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100'
  },
  {
    id: 2,
    name: 'Kofi T.',
    role: 'Enseignant, Kara',
    rating: 4.5,
    content: 'J\'avais besoin d\'informations sur les impôts et l\'assistant m\'a fourni toutes les réponses dont j\'avais besoin. C\'est comme avoir un expert fiscal disponible 24/7!',
    avatar: 'https://pixabay.com/get/g4ca4617de90b548e10d045e42755682b968ea6432807bc5ec92d6d5a613711c08a12888d619a75fbdba5278df3b62b9b292bb1f016402fd96c073ce89f8eb5cb_1280.jpg'
  },
  {
    id: 3,
    name: 'Afi D.',
    role: 'Commerçante, Atakpamé',
    rating: 5,
    content: 'L\'enregistrement de mon entreprise a été simplifié grâce à cette application. L\'assistant m\'a guidé étape par étape et m\'a aidé à économiser beaucoup de temps.',
    avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100'
  }
];
</script>

<template>
  <section class="py-20 bg-white">
    <div class="container mx-auto px-4 sm:px-6 lg:px-8">
      <div class="text-center mb-16">
        <h2 class="text-3xl md:text-4xl font-bold text-togo-dark mb-4">Témoignages des Utilisateurs</h2>
        <p class="text-lg text-togo-gray max-w-3xl mx-auto">Découvrez comment notre application a simplifié la vie administrative des citoyens togolais.</p>
      </div>
      
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
        <div
          v-for="testimonial in testimonials"
          :key="testimonial.id"
          class="bg-togo-light rounded-xl p-6 shadow-md hover:shadow-lg transition duration-300"
        >
          <div class="flex items-center mb-4">
            <div class="text-yellow-400 flex">
              <i 
                v-for="i in Math.floor(testimonial.rating)"
                :key="'star-full-'+i"
                class="fas fa-star"
              ></i>
              <i 
                v-if="testimonial.rating % 1 !== 0"
                class="fas fa-star-half-alt"
              ></i>
            </div>
            <span class="ml-2 text-sm text-togo-gray">{{ testimonial.rating.toFixed(1) }}</span>
          </div>
          <p class="text-togo-gray mb-6">"{{ testimonial.content }}"</p>
          <div class="flex items-center">
            <img 
              :src="testimonial.avatar" 
              :alt="`Portrait de ${testimonial.name}`" 
              class="w-12 h-12 rounded-full object-cover"
            />
            <div class="ml-3">
              <h4 class="font-bold text-togo-dark">{{ testimonial.name }}</h4>
              <p class="text-sm text-togo-gray">{{ testimonial.role }}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>
